# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required

before_install:
- curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: change
