// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// whats_my_name
void whats_my_name();
RcppExport SEXP SeqLib_whats_my_name() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    whats_my_name();
    return R_NilValue;
END_RCPP
}
// start_fermi
void start_fermi();
RcppExport SEXP SeqLib_start_fermi() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    start_fermi();
    return R_NilValue;
END_RCPP
}
// fermi
void fermi();
RcppExport SEXP SeqLib_fermi() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    fermi();
    return R_NilValue;
END_RCPP
}
