# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastqReader_Open <- function(f) {
    .Call('RSeqLib_fastqReader_Open', PACKAGE = 'RSeqLib', f)
}

createBamVector <- function() {
    invisible(.Call('RSeqLib_createBamVector', PACKAGE = 'RSeqLib'))
}

createBamRecord <- function() {
    invisible(.Call('RSeqLib_createBamRecord', PACKAGE = 'RSeqLib'))
}

alignSequence <- function(seq, name, hardclip, keep_sec_with_frac_of_primary_score, max_secondary) {
    invisible(.Call('RSeqLib_alignSequence', PACKAGE = 'RSeqLib', seq, name, hardclip, keep_sec_with_frac_of_primary_score, max_secondary))
}

load_index_from_sequence <- function(querySeq, seqname) {
    .Call('RSeqLib_load_index_from_sequence', PACKAGE = 'RSeqLib', querySeq, seqname)
}

load_index_from_fasta <- function(fasta) {
    .Call('RSeqLib_load_index_from_fasta', PACKAGE = 'RSeqLib', fasta)
}

run_bwa <- function(bwap, querySeq) {
    .Call('RSeqLib_run_bwa', PACKAGE = 'RSeqLib', bwap, querySeq)
}

