# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Fermi__new <- function() {
    .Call('_RSeqLib_Fermi__new', PACKAGE = 'RSeqLib')
}

Fermi__addReads <- function(fermi, qnames, seqs, quals) {
    invisible(.Call('_RSeqLib_Fermi__addReads', PACKAGE = 'RSeqLib', fermi, qnames, seqs, quals))
}

Fermi__correctReads <- function(fermi) {
    invisible(.Call('_RSeqLib_Fermi__correctReads', PACKAGE = 'RSeqLib', fermi))
}

Fermi__performAssembly <- function(fermi) {
    invisible(.Call('_RSeqLib_Fermi__performAssembly', PACKAGE = 'RSeqLib', fermi))
}

Fermi__getContigs <- function(fermi) {
    .Call('_RSeqLib_Fermi__getContigs', PACKAGE = 'RSeqLib', fermi)
}

BWA__new <- function() {
  .Call('_RSeqLib_BWA__new', PACKAGE = 'RSeqLib')
}

BWA__from_string <- function(xp, querySeq, seqname) {
    invisible(.Call('_RSeqLib_BWA__from_string', PACKAGE = 'RSeqLib', xp, querySeq, seqname))
}

BWA__from_fasta <- function(xp, fasta) {
    invisible(.Call('_RSeqLib_BWA__from_fasta', PACKAGE = 'RSeqLib', xp, fasta))
}

BWA__query <- function(xp, qstring, qname, hardclip, keep_sec_with_frac_of_primary_score, max_secondary) {
    .Call('_RSeqLib_BWA__query', PACKAGE = 'RSeqLib', xp, qstring, qname, hardclip, keep_sec_with_frac_of_primary_score, max_secondary)
}

fastqReader_Open <- function(f) {
    .Call('_RSeqLib_fastqReader_Open', PACKAGE = 'RSeqLib', f)
}

